# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["tulsashad@yahoo.com"] %>
  email_provider_api_key: <%= ENV["1L-MGEqtBK5IZRKM4dwNrQ"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["0f5c439b356b0570c83ea5f555f3d092-us12"] %>
  mailchimp_list_id: <%= ENV["ba6431e2a5"] %>
  owner_email: <%= ENV["shadmhill@fastmail.com"] %>
  secret_key_base: 9f6a0d7109d6ca3cd0111e2fc3322f47af8ee665d2f3a05ae83e33f1390449eca48b996d10e015b37c408274b2932916638d17fd320fc86fd17667805bf9f73c

test:
  secret_key_base: c15f99a59a1461b0970817252f05aabc0ab85813dece0f2cb8e990b3a9d52f7b5584eddc94ca643943d307f2672514cfe0b8a5e92f9f1514251264e8556257bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["tulsashad@yahoo.com"] %>
  email_provider_api_key: <%= ENV["1L-MGEqtBK5IZRKM4dwNrQ"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["0f5c439b356b0570c83ea5f555f3d092-us12"] %>
  mailchimp_list_id: <%= ENV["ba6431e2a5"] %>
  owner_email: <%= ENV["shadmhill@fastmail.com"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
